name: build and test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        working-directory: ./
        run: dotnet restore
      - name: Build
        working-directory: ./
        run: dotnet build --configuration Release --no-restore
      - name: CDK Unit Tests
        working-directory: ./tests/Rest.Api.Infrastructure.CDK.UnitTests
        run: dotnet test --no-restore --logger GitHubActions